CREATE COLUMN TABLE "ZCI_FSDM_FLOW_AUDIT" (
  "RUN_ID" NVARCHAR(80) NOT NULL,
  "STAGE_NAME" NVARCHAR(120) NOT NULL,
  "ENTITY_NAME" NVARCHAR(120),
  "TABLE_NAME" NVARCHAR(256),
  "KEY_VALUE" NVARCHAR(1000),
  "FAILURE_REASON" NVARCHAR(5000),
  "EXPECTED_JSON" NCLOB,
  "ACTUAL_JSON" NCLOB,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
